name: 'Git Updater Remote Trigger'
inputs:
  domain:
    description: 'Provide webiste domain e.g. example.com'
    required: true
  key:
    description: 'Git Updater key'
    required: true
  type:
    description: 'Accepts "theme" or "plugin"'
    required: true
  repo:
    description: 'Git repository name'
    required: true
  branch:
    description: 'Name of git branch configured on WP site'
    required: true
outputs:
  error-status:
    description: "Error status, 0 or 1"
    value: ${{ steps.wp-request.error-status }}
runs:
  using: "composite"
  steps:
    - id: wp-request
      shell: bash
      run: exit $(${{ github.action_path }}/request.sh "https://${{inputs.domain}}/wp-json/git-updater/v1/update/?key=${{inputs.key}}&${{inputs.type}}=${{inputs.repo}}&branch=${{inputs.branch}}")